#cloud-config
chpasswd:
  expire: false
  list: |
    admin:${tmos_admin_password}
tmos_dhcpv4_tmm:
  enabled: true
  rd_enabled: false
  icontrollx_trusted_sources: false
  inject_routes: true
  configsync_interface: ${configsync_interface}
  default_route_interface: ${default_route_interface}
  dhcp_timeout: 120
  dhcpv4_options:
    mgmt:
      host-name: ${hostname}
      domain-name: ${domain}
    '${default_route_interface}':
      routers: ${default_route_gateway}
  do_enabled: true
  do_declaration: ${do_local_declaration}
  do_declaration_url: ${do_declaration_url}
  do_declaration_url_headers:
    PRIVATE-TOKEN: x6VpQuWhiT_KgT3mzyTe
  do_template_variables:
    primary_dns: 8.8.8.8
    secondary_dns: 1.1.1.1
    timezone: Europe/Paris
    primary_ntp: 132.163.96.5
    secondary_ntp: 132.163.97.5
    primary_radius: 10.20.22.20
    primary_radius_secret: testing123
    secondary_radius: 10.20.23.20
    secondary_radius_secret: testing123
  as3_enabled: true
  as3_declaration_url: ${as3_declaration_url}
  as3_declaration_url_headers:
    PRIVATE-TOKEN: x6VpQuWhiT_KgT3mzyTe
  as3_template_variables:
    selfip_snat_address: 10.20.40.40
  ts_enabled: true
  ts_declaration_url: ${ts_declaration_url}
  ts_declaration_url_headers:
    PRIVATE-TOKEN: x6VpQuWhiT_KgT3mzyTe
  ts_template_variables:
    splunk_log_ingest: 10.20.23.30
    splunk_password: 0f29e5dc-bee8-4898-9054-9b66574a3e14
  phone_home_url: ${phone_home_url}
  phone_home_url_verify_tls: false
  phone_home_url_metadata:
    template_source: ${template_source}
    template_version: ${template_version}
    zone: ${zone}
    vpc: ${vpc}
    app_id: ${app_id}
  tgactive_url: ${tgactive_url}
  tgstandby_url: ${tgstandby_url}
  tgrefresh_url: ${tgrefresh_url}

