#! /bin/bash

set -e

USAGE="
NB: This script has been designed to be run from the repos root level directroy, as that is where it will be executed from in the pre-validation stage of the catalog onboarding pipeline.

The script will generate SSH keys and then append the public key to the catalogValidationValues.json file which is generated by the onboarding catalog pipeline before this script runs.

Usage (from repos root directory): ./tests/scripts/pre-validation-generate-ssh-key.sh <ssh_key_variable_name> <directory_of_json>

where:
<ssh_key_variable_name> = The name of the terraform variable which takes the SSH public key as input
<directory_of_json> = The directory where the catalogValidationValues.json file exists (will be the same directroy as the terraform code being onboarded)
"

if [ $# -eq 0 ]; then
  echo "No arguments supplied. See usage:"
  echo "${USAGE}"
  exit 1
fi

VAR_NAME=$1
DIR=$2

# Generate SSH keys and place in temp directory
temp_dir=$(mktemp -d)
ssh-keygen -f "${temp_dir}/id_rsa" -t rsa -N '' <<<y

# Extract public key value and delete temp directory
ssh_public_key=$(cat "${temp_dir}/id_rsa.pub")
rm -rf "${temp_dir}"

# Append the SSH public key value to the JSON file which will be used during catalog onboarding validation
json_file="${DIR}/catalogValidationValues.json"  # This gets created by pipeline code based on the catalogValidationValues.json.template
echo "Appending SSH public key to ${json_file}.."
jq -r --arg var_name "${VAR_NAME}" --arg ssh_public_key "${ssh_public_key}" '. + {($var_name): $ssh_public_key}' "${json_file}" > tmpfile && mv tmpfile "${json_file}" || exit 1

echo "Pre-validation complete successfully"
